import { StyleSheet } from 'react-native';
import { colors } from './commonStyles';

export const buttonStyles = StyleSheet.create({
    button: {
        backgroundColor: colors.sg2,
        borderRadius: 5,
        color: colors.sg2,
        borderColor: colors.sg5,
        display: "flex",
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        width: '100%',
        height: 52,
        textAlign: "center",
    },
    buttonIcon: {
        backgroundColor: colors.sg1,
        borderRadius: 5,
        color: colors.sg2,
        borderColor: colors.sg2,
        display: "flex",
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: 12,
        paddingHorizontal: 24,
        flexDirection: 'row',
        borderWidth: 1,
        width: '100%',
        height: 52,
        textAlign: "center",
    },
    searchBar: {
        borderRadius: 5,
        borderWidth: 1,
        borderColor: colors.sg5,
        color: colors.sg2,
        display: "flex",
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: 52,
        textAlign: "center",
    },
    buttonUI: {
        backgroundColor: colors.sg2,
        borderRadius: 5,
        color: colors.sg2,
        borderColor: colors.sg5,
        display: "flex",
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        width: '100%',
        height: 52,
        textAlign: "center",
        position: 'absolute',
        bottom: 0,
    },
    card: {
        position: "relative",
        color: colors.sg2,
        fontWeight: 'normal',
        borderRadius: 8,
        width: '100%',
        height: 80,
        marginVertical: 8,
        alignItems: 'center',
        overflow: 'hidden',
    },
    studentCard: {
        borderRadius: 10,
        padding: 4,
        marginVertical: 6,
        borderWidth: 1,
        borderColor: colors.sg2,
    },
    cardBackground: {
        width: '100%',
        height: '100%',
        margin: 0,
        borderRadius: 8,
    },
    cardImage: {
        backgroundColor: colors.sg2,
        borderRadius: 8,
        width: 64,
        height: 64,
        marginRight: 12,
    },
    overlay: {
        width: '100%',
        backgroundColor: "#00000080",
        textAlign: "center",
        position: "absolute",
        bottom: 0,
        zIndex: 1,
        padding: 10,
        borderBottomEndRadius: 8,
        borderBottomStartRadius: 8,
    },
    flatList: {
        width: '100%',
        height: '100%',
    },
    buttonBorder: {
        borderRadius: 5,
        color: colors.sg2,
        borderColor: colors.sg2,
        display: "flex",
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        width: '100%',
        height: 52,
        paddingHorizontal: 12,
    },
    buttonContent: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: "center",
    },
    onStep: {
        backgroundColor: colors.sg2,
        borderRadius: 50,
        color: colors.sg3,
        width: 72,
        height: 72,
        textAlign: "center",
        alignItems: "center",
    },
    offStep: {

    },
    buttonHalf: {
        backgroundColor: colors.sg2,
        borderRadius: 5,
        color: colors.sg2,
        borderColor: colors.sg5,
        display: "flex",
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        width: '50%',
        height: 52,
        textAlign: "center",
    }
})