import { StyleSheet } from 'react-native';
import { colors } from './commonStyles';

export const buttonStyles = StyleSheet.create({
    button: {
        backgroundColor: colors.sg2,
        borderRadius: 5,
        color: colors.sg2,
        borderColor: colors.sg5,
        display: "flex",
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        width: '100%',
        height: 52,
        textAlign: "center",
    },
    searchBar: {
        borderRadius: 5,
        borderWidth: 1,
        borderColor: colors.sg5,
        color: colors.sg2,
        display: "flex",
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: 52,
        textAlign: "center",
    },
    buttonUI: {
        backgroundColor: colors.sg2,
        borderRadius: 5,
        color: colors.sg2,
        borderColor: colors.sg5,
        display: "flex",
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        width: '100%',
        height: 52,
        textAlign: "center",
        position: 'absolute',
        bottom: 0,

    },
    card: {
        position: "relative",
        color: colors.sg2,
        fontWeight: 'normal',
        borderRadius: 8,
        width: '100%',
        height: 80,
        marginVertical: 8,
        alignItems: 'center',
        overflow: 'hidden',
    },
    cardBackground: {
        width: '100%',
        height: '100%',
        margin: 0,
        borderRadius: 8,
    },
    overlay: {
        width: '100%',
        backgroundColor: "#00000080",
        textAlign: "center",
        position: "absolute",
        bottom: 0,
        zIndex: 1,
        padding: 10,
        borderBottomEndRadius: 8,
        borderBottomStartRadius: 8,
    },
    flatList: {
        width: '100%',
        height: '100%',
    }
})